### ISSUE TITLE
Upload pictures

### ISSUE THREAD

**Issue by atomoc** [julianlam/nodebb-plugin-sso-google#14]
Uploading images is not used, yet I found a function in the file **src/user/picture.js** to download images. I do not have the knowledge to take advantage of this feature, please bring an example of its use.

**Comment by atomoc** [comment]
I'm talking about this part of the code: https://github.com/julianlam/nodebb-plugin-sso-google/blob/master/library.js#L121-L122

**Comment by atomoc** [comment]
It should look something like this: `User.uploadPicture(uid, picture);`

**Comment by julianlam** [comment]
Seems unrelated to this plugin...
