### ISSUE TITLE
missing option to disable sso registration

### ISSUE THREAD

**Issue by Pappmann** [julianlam/nodebb-plugin-sso-google#16]
missing option that only registered users can login via google sso

**Comment by julianlam** [comment]
If registration was disabled, how would you log in?  :stuck_out_tongue:

**Comment by Pappmann** [comment]
via local registration, sso bypass all forum resrictions (email invite for example)

**Comment by yariplus** [comment]
There should be an option to link the SSO login to an existing local account, or viceversa, and an option to require they enter an e-mail when a new forum account is created.

**Comment by Pappmann** [comment]
Yes an option that checks if email exists in group "registred" or "invited" , all other will be rejected.
