### ISSUE TITLE
redirect_uri_mismatch with nginx proxy

### ISSUE THREAD

**Issue by kdpuvvadi** [julianlam/nodebb-plugin-sso-google#19]
i've setup nginx proxy to the nodebb and i've setup /auth/google/callback in callback uri but it is redirecting to the localhost:4567/auth/google/callback and google apis throwing redirect_uri_mismatch error, how can i possibly solve this?

**Comment by julianlam** [comment]
Set `url` argument in `config.json` to your publicly accessible URL.
