### ISSUE TITLE
nodebb-plugin-sso-google and nodebb-plugin-sso-github ask to be upgraded to nonexistent 2.0.0 version

### ISSUE THREAD

**Issue by BenLubar** [julianlam/nodebb-plugin-sso-google#20]
![](https://what.thedailywtf.com/uploads/files/1464498947681-upload-9c9218a7-556b-4725-8291-1b6e3cda98e3.png)

I can't find any trace of version 2.0.0 on NPM or either GitHub repository.

**Comment by julianlam** [comment]
Odd, these routes say otherwise:
* https://packages.nodebb.org/api/v1/plugins/nodebb-plugin-sso-github
* https://packages.nodebb.org/api/v1/plugins/nodebb-plugin-sso-google

Though this one says latest is v2.0.0: https://packages.nodebb.org/api/v1/plugins?version=1.0.3

**Comment by julianlam** [comment]
Ah, I remember now, I accidentally published a major version not realising @psychobunny already incremented... back in January.

I can't unpublish it now because of the left-pad nonsense, so I'm going to have to publish v2.0.1, because raisins.

**Comment by julianlam** [comment]
Done :+1:
