### ISSUE TITLE
Menu location

### ISSUE THREAD

**Issue by joetm** [julianlam/nodebb-plugin-sso-google#21]
For this plugin and the other ones (e.g. Twitter SSO), could you move the "Social Authentication" menu item to the "Plugins" submenu? The "Social Authentication" takes a lot of screen space. And once it's set up, you really never need to visit it again.
If a submenu can't have other submenu, then I suggest to split it up into multiple menu items under the "Plugins" menu.

**Comment by yayacannes** [comment]
Same question please ;)

**Comment by julianlam** [comment]
@joetm only 3 years overdue :ok_hand:
