### ISSUE TITLE
404 Error on redirect during registration

### ISSUE THREAD

**Issue by mcumbers** [julianlam/nodebb-plugin-sso-google#23]
Hey there!

I've got an issue during registrations using Google that throws the user back to a 404 page after giving consent through Google. Looks like a pretty simple fix, but figured I'd make a post about it anyway.

When Google redirects back to the site with the OAuth code, it seems to be adding an extra # to the end of the URL. This is causing users registering with their Google+ to hit a 404 page and not complete their registration.

![capture1](https://cloud.githubusercontent.com/assets/16696023/18229145/b71ae658-7221-11e6-9441-01e8e164418d.PNG)

As soon as the # is removed, the registration completes normally, though. Just wondering if there's something I configured wrong, or if it's a fix that has to be made with the plugin?

Thanks!

**Comment by julianlam** [comment]
@mcumbers Can't say I've heard of this particular issue before, though it could be that something changed on the Google end of things.

**Comment by julianlam** [comment]
Unfortunately I cannot reproduce this issue. Have you tried creating a new set of OAuth 2.0 credentials?

What is the callback URL you've specified in the Google console?
