### ISSUE TITLE
Invalid Username

### ISSUE THREAD

**Issue by worp1900** [julianlam/nodebb-plugin-sso-google#25]
Internal error.
    Ups! Something went wrong!
    /auth/google/callback
    Invalid Username

Thought I'd create an issue ticket here as well, as the sso error for Google is different from the one for twitter. Google reports "Invalid username" where Twitter posts "Failed to find request token in session".

Mysterious. Especially since Facebook SSO works.

Could have figured a reverse proxy problem with usual Nginx in front of nodebb. But that would cause all SSO to fail, most likely, not just Google and Twitter.

Quote curious what that might be...

**Comment by worp1900** [comment]
Linking julianlam/nodebb-plugin-sso-twitter#23

**Comment by julianlam** [comment]
What username is it, anyway?

**Comment by worp1900** [comment]
That is a valid question. What username would he pull off of google?

It's a registration process, so at least forum-internally there shouldn't be a username yet, until the registration is complete.

**Comment by julianlam** [comment]
It would be the firstname and lastname as provided by Google. It depends on what the value is, though, perhaps there are some special characters that NodeBB won't allow.

**Comment by julianlam** [comment]
Thanks -- that may be significant. Ideally we'd allow the name with umlauts.

**Comment by snarlynarwhal** [comment]
Not sure if this is related, but I'm getting this error:

`/auth/facebook Not Found` shows as an alert.
`facebook:1 Failed to load resource: the server responded with a status of 404 ()` shows in the console.
