### ISSUE TITLE
Getting error when I try to login with Google: /auth/google Not Found

### ISSUE THREAD

**Issue by snarlynarwhal** [julianlam/nodebb-plugin-sso-google#29]
Getting the same with nodebb-plugin-sso-facebook.

In the Credentials section of Google Cloud Platform I have:

`https://forum.halfhumangames.com` for **Authorized JavaScript origins** and..

`https://forum.halfhumangames.com/auth/google/callback` for **Authorized redirect URIs**

**Comment by julianlam** [comment]
Sounds like the plugin is not properly instantiated or set up. Make sure the client ID and secrets are set in the plugin settings. Restart your NodeBB after saving the config.

**Comment by snarlynarwhal** [comment]
In case anyone encounters this, try rebuilding. I think something happened when rebuilding after activating the plugin, but after rebuilding again it worked.
