### ISSUE TITLE
Getting error when I try to login with Google: /auth/google Not Found (docs need update?)

### ISSUE THREAD

**Issue by snarlynarwhal** [julianlam/nodebb-plugin-sso-google#30]
Getting the same with nodebb-plugin-sso-facebook.

In the Credentials section of Google Cloud Platform I have:

`https://forum.halfhumangames.com` for **Authorized JavaScript origins** and..

`https://forum.halfhumangames.com/auth/google/callback` for **Authorized redirect URIs**

It looks like documentation might need updating if any step is missing or unclear.

**Comment by julianlam** [comment]
See #25

**Comment by snarlynarwhal** [comment]
In case anyone comes across this issue, you have to make sure you do `./nodebb build` after you install the plugin. @julianlam I think the readme could benefit from including this. When activating the plugins it asks you to restart, but you have to rebuild too.

**Comment by julianlam** [comment]
Woops, I meant, see #29
