### ISSUE TITLE
Getting Error: failed to fetch user profile when login in with Google

### ISSUE THREAD

**Issue by johnking** [julianlam/nodebb-plugin-sso-google#31]
I got an error after logging in with Google-sign-on
```
 Internal Error.

Oops! Looks like something went wrong!

/auth/google/callback

failed to fetch user profile
```

**Comment by johnking** [comment]
I resolved it by enabled google+ api,

**Comment by johnking** [comment]
I resolved it by enabling Google+ API, I thought I had done it.

**Comment by julianlam** [comment]
Thanks for following up! I'm sure it will help others who run into this issue :smile:
