### ISSUE TITLE
Deprecated Google+ API

### ISSUE THREAD

**Issue by RoiEXLab** [julianlam/nodebb-plugin-sso-google#32]
Just got the email that the Google+ SSO API will be shut down in favour of the newer non+ API: https://developers.google.com/+/api-shutdown

I'm not really familiar what, or even if something still needs to be changed here.
What I do know for certain though is that in any case the ACP description text needs to be updated accordingly.
Just thought I'd mention it.

**Comment by julianlam** [comment]
Oof, I have no idea, but I'm sure there will be movement on the passport-google project. It'll probably require some sort of refactor on this end, but thanks for the heads up!

**Comment by julianlam** [comment]
The OAuth login should work fine going forward actually, I don't think that part is getting shut down. However, I do need to update to use `passport-google-oauth20` instead of the metapackage I am currently using.

**Comment by winfredkqin** [comment]
> The OAuth login should work fine going forward actually, I don't think that part is getting shut down.

Hi @julianlam, actually Google officially said:

> The Google+ Sign-in feature has been fully deprecated and will also be shut down on **March 7, 2019**. Developers should [migrate](https://developers.google.com/identity/sign-in/web/quick-migration-guide) to the more comprehensive [Google Sign-in authentication system](https://developers.google.com/identity/)

**Comment by julianlam** [comment]
The link you pasted links out to here: https://developers.google.com/identity/protocols/OAuth2

**Comment by julianlam** [comment]
v2.3.0 contains a dependency change and uses new user endpoint that should continue working past the deprecation.
