### ISSUE TITLE
"Google Sign-In Branding" Issue

### ISSUE THREAD

**Issue by winfredkqin** [julianlam/nodebb-plugin-sso-google#33]
Nowadays, Google introduces human-review when any project applies to integrate with Google Sign-in service.

I received an email today, saying:

> The Google sign-in button on your project's homepage URL is not compliant with the Google sign-in branding guidelines. Please update the Google sign-in button on your website according to [Google sign-in branding guidelines](https://developers.google.com/identity/branding-guidelines#top_of_page).

I checked the source code. Currently, the Google icon is using

`<i class="fa fa-google-plus-square fa-2x"></i>`

So as Google insists, it may have to be replaced with Google's official icon.

I'll do the modification and test it in my project. If it does work, may I merge my code into the master branch?

**Comment by winfredkqin** [comment]
@julianlam I just realized that. I guess I'm going to modify NodeBB part. But this may introduce trouble when updating. Unhappy.

**Comment by julianlam** [comment]
Yes indeed... Now, what you could do is change the underlying system itself. The `filter:auth.init` calls each registered SSO plugin for their strategy object, and it passes in the icon name there. However, it doesn't pass an `iconType` because we only meant for it to use fontawesome. You could set `iconType` to `image`, and then pass in the appropriate branding.

Then in NodeBB core, you'd change it so that if `iconType` is not present or `fontawesome`, then it uses the fontawesome icon, and add appropriate handling for images.

However, it is indeed a much larger task than you originally envisioned :confused:

**Comment by julianlam** [comment]
https://github.com/NodeBB/nodebb-theme-persona/blob/master/templates/login.tpl#L57-L59

FontAwesome is blindly assumed here, but the logic can be altered to support both FontAwesome or a plain image, theoretically...

**Comment by winfredkqin** [comment]
I'm thinking to modify theme tempate rather than NodeBB core. It avoids the trouble of introducing `iconType` parameter. Although this will be ugly.

Thanks for your tips.

**Comment by julianlam** [comment]
@winfredkqin -- I just realized there is an easy (albeit slightly hacky) way of skirting around this issue.

The skeleton OAuth plugin I use passes in the fa-check icon. It is possible to add a client-side selector to detect this icon (on the login/register pages) and replace it with the appropriate Google branding.

**Comment by julianlam** [comment]
You'll have to change your code so it is executed when action:ajaxify.end event is called against $(window)

**Comment by navixco** [comment]
Thanks @julianlam and Google :).
At last Google had approved my website.
--
JS:
function hasClass(el, className) {
  if (el.classList)
    return el.classList.contains(className)
  else
    return !!el.className.match(new RegExp('(\\s|^)' + className + '(\\s|$)'))
}

function addClass(el, className) {
  if (el.classList)
    el.classList.add(className)
  else if (!hasClass(el, className)) el.className += " " + className
}

function removeClass(el, className) {
  if (el.classList)
    el.classList.remove(className)
  else if (hasClass(el, className)) {
    var reg = new RegExp('(\\s|^)' + className + '(\\s|$)')
    el.className=el.className.replace(reg, ' ')
  }
}

function  changeClass(){
    
     var el = document.getElementsByClassName('google')
 var i;
 for (i = 0; i < el.length; i++) {
     //el[i].style.backgroundColor = "red";
    addClass(el[i], 'google-btn');
    removeClass(el[i], 'google');
 }

  el = document.getElementsByClassName('fa-google-plus-square')
 for (i = 0; i < el.length; i++) {
    addClass(el[i], 'google-btn');
    removeClass(el[i], 'fa-google-plus-square');
 }

} //end changeClass

$(window).on('action:ajaxify.end', changeClass);

**Comment by winfredkqin** [comment]
@julianlam Thank for your suggestion.

I've worked around by this approach (ugly): Modify theme file directly with an offical icon picture.

# Steps:

In the directory `node_modules/<nodebb-theme>/templates` -> `login.tpl` & `register.tpl`:

Replace the line similar as:

```
<!-- IF alternate_logins -->
	<div class="<!-- IF allowLocalLogin -->col-md-6<!-- ELSE -->col-md-12<!-- ENDIF allowLocalLogin -->">
		<div class="alt-login-block">
			<h4>[[login:alternative_logins]]</h4>
			<ul class="alt-logins">
				<!-- BEGIN authentication -->
				<li class="{authentication.name}"><a rel="nofollow noopener noreferrer" target="_top" href="{config.relative_path}{authentication.url}">

[MODIFY THIS!] <i class="fa {authentication.icon} fa-3x"></i></a></li> [MODIFY THIS!]

				<!-- END authentication -->
			</ul>
		</div>
	</div>
<!-- ENDIF alternate_logins -->
```

with:

`<img style="height:4em;" alt="Sign in with Google" src="your_google_button_image.svg" />`

**Comment by julianlam** [comment]
v2.4.0
