### ISSUE TITLE
Google 2019 logo instead of Google+ logo

### ISSUE THREAD

**Issue by yayacannes** [julianlam/nodebb-plugin-sso-google#39]
How can we change this little Google+ logo by a big and new Google logo please ?

Very Thanks for this plugin by the way !

**Comment by julianlam** [comment]
Can you share the asset here please? It should be a fairly simple update to the existing asset, a PR is always welcome if you are able.

**Comment by yayacannes** [comment]
![Capture d’écran 2019-11-26 à 17 55 56](https://user-images.githubusercontent.com/29663813/69655063-1a33a900-1076-11ea-898c-e765bc7ee2ae.jpg)

I will prefer something like :
![connectwithgoogle](https://user-images.githubusercontent.com/29663813/69655185-523aec00-1076-11ea-8e01-83078130311b.png)

Very thanks !

**Comment by julianlam** [comment]
We already use this logo: https://github.com/julianlam/nodebb-plugin-sso-google/blob/master/static/images/btn_google_signin_light_normal_web.png
