### ISSUE TITLE
Automatic User Validation Not Working

### ISSUE THREAD

**Issue by shayanYousefi** [julianlam/nodebb-plugin-sso-google#45]
When the option for skipping email verification is on, the users are not validated, so what the can do in forum is restricted.

![image](https://user-images.githubusercontent.com/13784931/121775686-5ff38c00-cb9e-11eb-8074-8caf7da472d7.png)

![image](https://user-images.githubusercontent.com/13784931/121775729-9d581980-cb9e-11eb-9fb4-70bdd781c32a.png)

**Comment by julianlam** [comment]
Hi @shayanYousefi -- unfortunately I am not able to reproduce this issue. Using latest NodeBB (v1.17.1, master) and sso-google@2.5.4, I successfully registered and the account was automatically confirmed.

Could it be that when you saved the setting, you did not restart NodeBB?

**Comment by shayanYousefi** [comment]
It seems the problem was fixed with #44.
