### ISSUE TITLE
Plugin Configuration page

### ISSUE THREAD

**Issue by Sanando1989** [julianlam/nodebb-plugin-sso-google#46]
As mentioned in configuration, we need to configure client id and secret id in plugin configuration page. where I get this plugin file.
I have configured already nodebb locally. How we will set up the client id and secret id. Please let me  know.

Thanks in Advance.

**Comment by julianlam** [comment]
Hi @Sanando1989 -- once you install and activate the plugin, the settings page is accessible from within NodeBB's ACP, under "Plugins" submenu.
