### ISSUE TITLE
Missing required parameter Scope

### ISSUE THREAD

**Issue by Radiergummi** [julianlam/nodebb-plugin-sso-google#8]
Seems like Google changed some things about their API, since I could find some other people with projects using the passport library which had the same problem. When authenticating with Google+, the following error page appears:
![bildschirmfoto 2015-05-30 um 19 58 09](https://cloud.githubusercontent.com/assets/6115429/7898641/55e2a72c-0706-11e5-8ea0-31339d0171a0.png)

Any idea? Have not modified the plugin nor can I relate it to a recent NodeBB change I made.

**Comment by julianlam** [comment]
Thanks, which scope parameter is required? seems like an easy fix.

**Comment by Radiergummi** [comment]
I'm sorry, my bad. Seems like I confused my API keys. Thanks for the quick response, anyway :smile:
