### ISSUE TITLE
NodeBB v0.7.0, v0.6.0 Compatibility? Plugin redirects to "Guest" account upon authentication

### ISSUE THREAD

**Issue by metahusk** [julianlam/nodebb-plugin-sso-google#9]
I've been using NodeBB for a while now and I love it. It seems 6 months ago the auth plugins stopped working for me.

I can log into existing accounts sso-google, sso-facebook (didn't try twitter) but if I try to register new accounts it seems to succeed but the user is logged in as "guest" and no categories or threads are visible. If I click logout of the "guest" account everything appears as normal.

I checked the list of users in NodeBB and no new user was created. There were no error messages displayed.

Here is a screenshot. 
![Guest Account](http://s23.postimg.org/z1q46vju3/sso_google.jpg "Guest Account")

I have the same problem with the Facebook and Twitter plugin.

Setup: NodeBB v0.7.0  Ubuntu 14.04 Redis and using NGINX as a reverse proxy. I tried Firefox, IE, and Chrome. They all have the same results. I tried IP:Port to bypass NGINX but still had the same problem. I would try to change Google's callback settings but they only allow a callback to top level domains not IP:Port.

Thanks for your awesome work! I'm very impressed with your projects.

**Comment by julianlam** [comment]
Let me know if this issue persists. Thanks!
